language: java

jdk:
  - oraclejdk8
    sudo: false

  before_script:
    - echo "Starting build"
  scrypt:
    - mvn clean package
  after_script:
    - echo "Script finished"

   after_failure:
    - echo "Build was failed"
    after_success:
      - bash <(curl -s https://codecov.io/bash)




notifications:
  email:
    recipients:
    - emelyanov.daniil93@gmail.com
    on_success: never # default: change
    on_failure: always # default: always