language: java


sudo: false
jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
    - emelyanov.daniil93@gmail.com
    on_success: never # default: change
    on_failure: always # default: always