language: java


sudo: false
branches:
  only:
    - master
    - /^release.*$/

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
    - emelyanov.daniil93@gmail.com
    on_success: never # default: change
    on_failure: always # default: always