language: java
jdk:
  - oraclejdk8
before install:
if [[ \"$TRAVIS_OS_NAME\" == \"linux\" ]]; then sudo apt-get -qq update ; fi,
if [[ \"$TRAVIS_OS_NAME\" == \"linux\" ]]; then sudo apt-get install -y lib32z1 lib32ncurses5 ; fi
notifications:
  email:
    recipients:
    - emelyanov.daniil93@gmail.com
    on_success: never # default: change
    on_failure: always # default: always