language: java
sudo: false

jdk:
  - oraclejdk8
  fixes: - "io/github/config4k::src/main/io.github.config4k"
after_success:
      - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
    - emelyanov.daniil93@gmail.com
    on_success: never # default: change
    on_failure: always # default: always